# Generated by Django 4.2.6 on 2023-10-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreP', models.TextField(max_length=120)),
                ('direccion', models.TextField(max_length=20)),
                ('telefono', models.SmallIntegerField(max_length=10)),
                ('fecha_creacion', models.DateField()),
                ('estado', models.SmallIntegerField(max_length=1)),
            ],
        ),
    ]
