# Generated by Django 4.2.6 on 2023-10-21 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cita_medica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha_creacion',
            new_name='fecha_registro',
        ),
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Sí')], default=0),
        ),
        migrations.AddField(
            model_name='paciente',
            name='antecedentes',
            field=models.CharField(default='Sin antecedentes', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.TextField(default='Masculino', max_length=8),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_sangre',
            field=models.CharField(default='O+', max_length=3),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombreP',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.SmallIntegerField(),
        ),
    ]
