# Generated by Django 4.2.6 on 2023-11-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita_medica', '0008_reservacita_remove_doctor_user_delete_cita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacita',
            name='tipo_cita',
            field=models.CharField(choices=[('Examen', 'Examen Médico'), ('Consulta', 'Consulta General'), ('Especialista', 'Consulta Especialista')], default='Consulta General', max_length=50),
        ),
    ]
