# Generated by Django 4.2.6 on 2023-11-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita_medica', '0009_reservacita_tipo_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacita',
            name='tipo_cita',
            field=models.CharField(max_length=50),
        ),
    ]
