# Generated by Django 4.2.6 on 2023-11-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita_medica', '0010_alter_reservacita_tipo_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacita',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
