# Generated by Django 4.2.6 on 2023-11-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita_medica', '0012_paciente_alter_reservacita_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
